WebAppProject/ViewModels/CourseViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAppProject.ViewModels
{
    public class CourseViewModel
    {
        public int Id { get; set; }

        [MinLength(2, ErrorMessage = "Name must be at least 2 characters.")]
        [RegularExpression(@"[a-zA-Z-#+]+", ErrorMessage = "Name must contain only [characters, # , + , -]")]
        public string Name { get; set; }

        [MinLength(4, ErrorMessage = "Name must be 4 characters or more.")]
        public string Description { get; set; }
    }
}

WebAppProject/Areas/Admin/Controllers/CourseController.cs
using AutoMapper;
using DataAccessLibrary.Interfaces;
using DataAccessLibrary.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppProject.ViewModels;



namespace WebAppProject.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area(areaName: "Admin")]
    public class CourseController : Controller
    {

        private readonly ICourseRepository courseRepository;
        private readonly IMapper _mapper;

        public CourseController(ICourseRepository courseRepository, IMapper mapper)
        {
            this.courseRepository = courseRepository;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            List<Course> courses = await courseRepository.GetAllAsync();
            var model = _mapper.Map<IEnumerable<CourseViewModel>>(courses);
            return View(model);
        }
        public async Task<IActionResult> Details(int Id)
        {
            IActionResult actionResult;
            Course? course = await courseRepository.GetByIdAsync(Id);
            if (course != null)
            {
                var model = _mapper.Map<CourseViewModel>(course);
                actionResult = View(model);
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CourseViewModel model)
        {
            IActionResult actionResult;
            if (ModelState.IsValid)
            {
                var course = _mapper.Map<Course>(model);
                int res = await courseRepository.AddAsync(course);
                actionResult = res > 0 ? RedirectToAction("Index") : RedirectToAction("Create");
            }
            else
            {
                actionResult = View(model);
            }
            return actionResult;
        }

        public async Task<IActionResult> Edit(int Id)
        {
            IActionResult actionResult;
            Course? course = await courseRepository.GetByIdAsync(Id);
            if (course != null)
            {
                var model = _mapper.Map<CourseViewModel>(course);
                actionResult = View(model);
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CourseViewModel model)
        {
            IActionResult actionResult;
            if (ModelState.IsValid)
            {
                var course = _mapper.Map<Course>(model);
                bool res = await courseRepository.UpdateAsync(course);
                actionResult = res ? RedirectToAction("Index") : RedirectToAction("Edit", model.Id);
            }
            else
            {
                actionResult = RedirectToAction("Edit", model.Id);
            }
            return actionResult;
        }

        public async Task<IActionResult> Delete(int Id)
        {

            IActionResult actionResult;
            Course? course = await courseRepository.GetByIdAsync(Id);
            if (course != null)
            {
                var model = _mapper.Map<CourseViewModel>(course);
                actionResult = View(model);
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }
        [HttpPost]
        public async Task<IActionResult> Delete(CourseViewModel model)
        {
            IActionResult actionResult;
            Course? course = await courseRepository.GetByIdAsync(model.Id);
            if (course != null)
            {
                await courseRepository.DeleteAsync(course.Id);
                actionResult = RedirectToAction("Index");
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }
    }



}

WebAppProject/Areas/Admin/Views/Course/CourseForm.cshtml
@model CourseViewModel

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">@ViewData["FormTitle"]</p>
                <div class="row">
                    <div class="col-12">
                        <form method="post" class="forms-sample">
                            <div class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Confirm" class="btn btn-primary mr-2" />
                                <a asp-action="Index" asp-controller="Course" class="btn btn-light">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebAppProject/Areas/Admin/Views/Course/Create.cshtml
@{
    ViewData["Title"] = "Create Course - Examly";
    ViewData["FormTitle"] = "Create Course";
}
<indicator hidden>admin-courses</indicator>
<partial name="CourseForm" />

WebAppProject/Areas/Admin/Views/Course/Delete.cshtml
@model CourseViewModel
@{
    ViewData["Title"] = "Delete Course - Examly";
}
<indicator hidden>admin-courses</indicator>
<div class="row justify-content-center">
    <div class="col-md-8 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Delete Cousre</p>
                <div class="row">
                    <div class="col-12">
                        <h4 class="card-text"> Are you sure you want to delete <strong>@Model.Name Course?</strong></h4>
                        <form method="post" class="forms-sample  mt-3">
                            <div class="form-group ">
                                <input type="submit" value="Delete" class="btn btn-danger mr-2" />
                                <a asp-action="Index" asp-controller="Course" class="btn btn-light">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebAppProject/Areas/Admin/Views/Course/Details.cshtml
@model CourseViewModel
@{
    ViewData["Title"] = "Course Details - Examly";
}
<indicator hidden>admin-courses</indicator>
<div class="row justify-content-center">
    <div class="col-md-8 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <p class="card-title m-0">Course Details</p>
                    <div>
                        <a asp-action="Edit" asp-controller="Course" asp-route-Id="@Model.Id" class="btn btn-inverse-primary btn-rounded btn-icon ml-1 align-content-center">
                            <i class="mdi mdi-pencil"></i>
                        </a>
                        <a asp-action="Delete" asp-controller="Course" asp-route-Id="@Model.Id" class="btn btn-inverse-danger btn-rounded btn-icon ml-1 align-content-center">
                            <i class="mdi mdi-delete"></i>
                        </a>
                        <a asp-action="Index" asp-controller="Course"
                           class="btn btn-inverse-dark btn-rounded btn-icon ml-1 align-content-center">
                            <i class="mdi mdi-close"></i>
                        </a>

                    </div> 
                </div>
                <div class="row">
                    <div class="col-12">
                        <p class="card-text">ID: <strong> @Model.Id</strong> </p>
                        <p class="card-text">Name: <strong>@Model.Name </strong></p>
                        <p class="card-text">Description: <strong>@Model.Description </strong></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebAppProject/Areas/Admin/Views/Course/Edit.cshtml
@{
    ViewData["Title"] = "Edit Course - Examly";
    ViewData["FormTitle"] = "Edit Course";
}
<indicator hidden>admin-courses</indicator>
<partial name="CourseForm" />

WebAppProject/Areas/Admin/Views/Course/Index.cshtml
@model List<CourseViewModel>
@{
    ViewData["Title"] = "Examly";
    Layout = "_DesignLayout";
}
<indicator hidden>admin-courses</indicator>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <p class="card-title m-0">Courses</p>
                    <a type="button"
                       asp-action="Create" asp-controller="Course"
                       class="btn btn-inverse-primary btn-icon-text">
                        <i class="mdi mdi-plus btn-icon-prepend d-inline-block"></i>
                        Add Course
                    </a>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table display expandable-table">
                                <thead >
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Operations</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model?.Count > 0)
                                    {
                                        foreach (var crs in Model)
                                        {
                                            <tr>
                                                <td>@crs.Id</td>
                                                <td>@crs.Name</td>
                                                <td>
                                                    <a asp-action="Details" asp-controller="Course" asp-route-Id="@crs.Id" class="btn btn-inverse-dark btn-rounded btn-icon ml-1 align-content-center">
                                                        <i class="mdi mdi-information-variant"></i>
                                                    </a>
                                                    <a asp-action="Edit" asp-controller="Course" asp-route-Id="@crs.Id" class="btn btn-inverse-primary btn-rounded btn-icon ml-1 align-content-center">
                                                        <i class="mdi mdi-pencil"></i>
                                                    </a>
                                                    <a asp-action="Delete" asp-controller="Course" asp-route-Id="@crs.Id" class="btn btn-inverse-danger btn-rounded btn-icon ml-1 align-content-center">
                                                        <i class="mdi mdi-delete"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="3">No Courses yet</td>
                                        </tr>

                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                 </div>
            </div>
        </div>
    </div>
</div>