WebAppProject/Areas/Admin/ViewModels/InstructorViewModel.cs
namespace WebAppProject.Areas.Admin.ViewModels
{
    public class InstructorViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string? BranchName { get; set; }
        public string? ManagedDepartmentName { get; set; }

    }
}

WebAppProject/Areas/Staff/ViewModels/StudentAnswersViewModel.cs
using WebAppProject.ViewModels;

namespace WebAppProject.Areas.Staff.ViewModels
{
    public class StudentAnswersViewModel
    {
        public string QuestionText { get; set; }
        public int QuestionGrade { get; set; }
        public List<ChoiceViewModel> CorrectChoices { get; set; }
        public List<ChoiceViewModel> StudentChoices { get; set; }
        public bool IsCorrect { get; set; }
    }
}

WebAppProject/ViewModels/StudentAnswersViewModel.cs
namespace WebAppProject.ViewModels
{
    public class StudentAnswersViewModel
    {
        public string QuestionText { get; set; }
        public int QuestionGrade { get; set; }
        public List<ChoiceViewModel> CorrectChoices { get; set; }
        public List<ChoiceViewModel> StudentChoices { get; set; }
        public bool IsCorrect { get; set; }
    }
}

WebAppProject/Areas/Admin/Controllers/InstructorController.cs
using AutoMapper;
using DataAccessLibrary.Interfaces;
using DataAccessLibrary.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppProject.Areas.Admin.ViewModels;

namespace WebAppProject.Areas.Admin.Controllers
{

    [Authorize(Roles = "Admin")]
    [Area(areaName: "Admin")]
    public class InstructorController : Controller
    {
        private readonly IInstructorRepository instructorRepository;
        private readonly IBranchRepository branchRepository;
        private readonly IUserRepository userRepository;
        private readonly IMapper _mapper;

        public InstructorController(IInstructorRepository instructorRepository, IBranchRepository branchRepository,
                                    IUserRepository userRepository, IMapper mapper)
        {
            this.instructorRepository = instructorRepository;
            this.branchRepository = branchRepository;
            this.userRepository = userRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Details(int Id)
        {
            IActionResult actionResult;
            Instructor? instructor = await instructorRepository.GetByIdWithIncludesAsync(Id);
            if (instructor != null)
            {
                var model = _mapper.Map<InstructorViewModel>(instructor);
                actionResult = View(model);
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }

        public async Task<IActionResult> Create()
        {
            List<Branch> branches = await branchRepository.GetAllAsync();
            var branchesDtos = _mapper.Map<List<BranchViewModel>>(branches);
            var model = new InstructorFormViewModel() { Branches = branchesDtos };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(InstructorFormViewModel model)
        {
            IActionResult actionResult;
            if (ModelState.IsValid)
            {
                var user = new User() { Email = model.Email, Password = model.Password, RoleId = 3 };
                int userId = await userRepository.AddAsync(user);
                if (userId != 0)
                {
                    var instructorDto = _mapper.Map<Instructor>(model);
                    instructorDto.UserId = userId;
                    int res = await instructorRepository.AddAsync(instructorDto);
                    actionResult = res > 0 ? RedirectToAction("Index", "Manage") : RedirectToAction("Create");
                }
                else
                {
                    actionResult = RedirectToAction("Create");
                }
            }
            else
            {
                var branches = await branchRepository.GetAllAsync();
                model.Branches = _mapper.Map<List<BranchViewModel>>(branches);
                actionResult = View(model);
            }
            return actionResult;
        }

        public async Task<IActionResult> Edit(int Id)
        {
            IActionResult actionResult = BadRequest();

            Instructor? instructor = await instructorRepository.GetByIdWithIncludesAsync(Id);
            if (instructor != null)
            {
                List<Branch> branches = await branchRepository.GetAllAsync();
                var branchesDtos = _mapper.Map<List<BranchViewModel>>(branches);
                var model = _mapper.Map<InstructorFormViewModel>(instructor);
                model.Branches = branchesDtos;
                actionResult = View(model);
            }
            return actionResult;
        }

        [HttpPost]
        public async Task<IActionResult> Edit(InstructorFormViewModel model)
        {
            IActionResult actionResult;
            if (ModelState.IsValid)
            {
                var instructor = _mapper.Map<Instructor>(model);
                bool res = await instructorRepository.UpdateAsync(instructor);
                actionResult = res ? RedirectToAction("Index", "Manage") : RedirectToAction("Edit", model.Id);
            }
            else
            {
                var branches = await branchRepository.GetAllAsync();
                model.Branches = _mapper.Map<List<BranchViewModel>>(branches);
                actionResult = View(model);
            }
            return actionResult;
        }

        public async Task<IActionResult> Delete(int Id)
        {
            IActionResult actionResult = BadRequest();

            Instructor? instructor = await instructorRepository.GetByIdAsync(Id);
            if (instructor != null)
            {
                var model = _mapper.Map<InstructorViewModel>(instructor);
                actionResult = View(model);
            }
            return actionResult;
        }

        [HttpPost]
        public async Task<IActionResult> Delete(InstructorViewModel model)
        {
            IActionResult actionResult;
            Instructor? instructor = await instructorRepository.GetByIdAsync(model.Id);
            if (instructor != null)
            {
                await instructorRepository.DeleteAsync(instructor.Id);
                actionResult = RedirectToAction("Index", "Manage");
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }
    }
}

WebAppProject/Areas/Staff/Controllers/InstructorController.cs
using AutoMapper;
using DataAccessLibrary.Interfaces;
using DataAccessLibrary.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using WebAppProject.Areas.Staff.ViewModels;
using WebAppProject.ViewModels;


namespace WebAppProject.Areas.Staff.Controllers
{
    [Authorize(Roles = "Manager,Instructor")]
    [Area(areaName: "Staff")]
    public class InstructorController : Controller
    {

        private readonly IInstructorRepository _instructorRepo;
        private readonly IExamRepository _examRepo;
        private readonly IQuestionRepository _questionRepo;
        private readonly IStudentRepository _studentRepo;
        private readonly IExamTakenRepository _examTakenRepo;
        private readonly IMapper _mapper;
        private Random _random;
        private readonly int _instId;

        public InstructorController(IInstructorRepository instructorRepo,
                                    IExamRepository examRepo,
                                    IQuestionRepository questionRepo,
                                    IStudentRepository studentRepo,
                                    IExamTakenRepository examTakenRepo,
                                    IHttpContextAccessor accessor,
                                    IMapper mapper)
        {
            _instructorRepo = instructorRepo;
            _examRepo = examRepo;
            _questionRepo = questionRepo;
            _studentRepo = studentRepo;
            _examTakenRepo = examTakenRepo;
            _mapper = mapper;
            _random = new Random();
            _instId = int.Parse(accessor.HttpContext!.User.Claims.FirstOrDefault(c => c.Type == "id")!.Value);
        }

        public async Task<IActionResult> Index()
        {
            var instructor = await _instructorRepo.GetByIdWithCourses(_instId).FirstOrDefaultAsync();

            if (instructor == null)
            {
                return NotFound();
            }

            IEnumerable<DeptCourseViewModel> deptCourses =
                _mapper.Map<IEnumerable<DeptCourseViewModel>>(instructor.DepartmentCourses);

            return View(deptCourses);
        }

        public async Task<IActionResult> Info(int id)
        {
            var deptCourses = await _instructorRepo.GetByIdWithCourses(_instId)
                                .Select(e => e.DepartmentCourses.Where(e => e.CourseId == id))
                                .FirstOrDefaultAsync();
            var deptCourse = deptCourses?.ElementAt(0);

            if (deptCourse == null)
            {
                return NotFound();
            }

            var deptCourseViewModel = _mapper.Map<DeptCourseViewModel>(deptCourse);
            return View(deptCourseViewModel);
        }

        public async Task<IActionResult> QuestionBank(int id)
        {
            ViewBag.CourseId = id;
            var questions = await _instructorRepo.GetCourseQuestionsAsync(_instId, id);

            if (questions == null)
            {
                return NotFound();
            }

            IEnumerable<QuestionViewModel> model =
                _mapper.Map<IEnumerable<QuestionViewModel>>(questions);

            return View(model);
        }

        [HttpGet]
        public IActionResult AddQuestion(int courseId)
        {
            var model = new QuestionViewModel() { CourseId = courseId, InstructorId = _instId };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddQuestion(int courseId, QuestionViewModel questionVM)
        {
            if (ModelState.IsValid)
            {
                if (questionVM.Choices.Count == 2)
                {
                    questionVM.Choices[0].IsCorrect = true;
                }

                var questionDto = _mapper.Map<Question>(questionVM);
                await _instructorRepo.AddQuestionAsync(questionDto);
                return RedirectToAction("QuestionBank", new { id = courseId });
            }

            return View(questionVM);
        }

        public IActionResult AddChoices(int id)
        {
            var model = new QuestionViewModel();
            if (id == 1)
            {
                model.Choices.AddRange(
                        [
                            new ChoiceViewModel(),
                            new ChoiceViewModel(),
                            new ChoiceViewModel(),
                            new ChoiceViewModel()
                        ]
                        );
                return PartialView("MCQChoicesPartial", model);
            }
            else
            {
                model.Choices.AddRange([new ChoiceViewModel(), new ChoiceViewModel()]);
                return PartialView("TFChoicesPartial", model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditQuestion(int id)
        {
            var question = await _questionRepo.GetByIdAsync(id);
            if (question == null)
            {
                return NotFound();
            }
            var questionViewModel = _mapper.Map<QuestionViewModel>(question);
            return View(questionViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditQuestion(QuestionViewModel questionVM)
        {
            if (ModelState.IsValid)
            {
                if (questionVM.Choices.Count == 2)
                {
                    questionVM.Choices[0].IsCorrect = true;
                }
                var questionDto = _mapper.Map<Question>(questionVM);
                await _questionRepo.UpdateAsync(questionDto);
                return RedirectToAction("QuestionBank", new { id = questionVM.CourseId });
            }

            return View(questionVM);
        }

        public async Task<IActionResult> QuestionInfo(int id)
        {
            var question = await _questionRepo.GetByIdCourseIncludedAsync(id);

            if (question == null)
            {
                return NotFound();
            }

            var questionViewModel = _mapper.Map<QuestionViewModel>(question);

            return View(questionViewModel);
        }

        public async Task<IActionResult> DeleteQuestion(int id, int qId)
        {
            await _questionRepo.DeleteAsync(qId);
            return RedirectToAction("QuestionBank", new { id });
        }

        [HttpGet]
        public async Task<IActionResult> MakeExam(int courseId, int deptId)
        {
            if (courseId == 0)
            {
                // TODO: user proper page
                return NotFound();
            }
            var questions = await _questionRepo.GetInstQuestionsAsync(courseId, _instId);
            var mcqDifficultyG = questions.Where(e => e.Type == QType.MCQ)
                                      .GroupBy(q => q.Difficulty)
                                      .OrderBy(q => (int)q.Key)
                                      .ToList();
            var tfDifficultyG = questions.Where(e => e.Type == QType.TrueFalse)
                                      .GroupBy(q => q.Difficulty)
                                      .OrderBy(q => (int)q.Key)
                                      .ToList();

            int[] mcqDifficultyCounts = new int[3];
            for (int i = 0; i < mcqDifficultyG.Count(); i++)
            {
                int index = ((int)mcqDifficultyG[i].Key) - 1;
                mcqDifficultyCounts[index] = mcqDifficultyG[i].Count();
            }
            int[] tfDifficultyCounts = new int[3];
            for (int i = 0; i < tfDifficultyG.Count(); i++)
            {
                int index = ((int)tfDifficultyG[i].Key) - 1;
                tfDifficultyCounts[index] = tfDifficultyG[i].Count();
            }

            if (mcqDifficultyCounts.Sum() + tfDifficultyCounts.Sum() == 0)
            {
                return NoContent();
            }

            var model = new InstExamViewModel()
            {
                CourseId = courseId,
                TotalMCQ = mcqDifficultyCounts,
                TotalTF = tfDifficultyCounts,
                NoOfMCQ = new int[3],
                NoOfTF = new int[3],
                DepartmentId = deptId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> MakeExam(InstExamViewModel instExamVM)
        {
            if (ModelState.IsValid && (instExamVM.NoOfMCQ.Sum() + instExamVM.NoOfTF.Sum() > 0))
            {
                var allQuestionsDto = await _questionRepo.GetInstQuestionsAsync(instExamVM.CourseId, _instId);

                // Separate true/false and multiple choice questions
                var mcqQuestionsDto = new List<Question>();
                var tfQuestionsDto = new List<Question>();

                for (int i = 0; i < 3; i++)
                {
                    if (instExamVM.NoOfMCQ[i] != 0)
                    {
                        var questions = allQuestionsDto.Where(q => q.Type == QType.MCQ && q.Difficulty == (QDifficulty)(i + 1))
                                                      .OrderBy(q => _random.Next())
                                                      .Take(instExamVM.NoOfMCQ[i])
                                                      .ToList();
                        mcqQuestionsDto.AddRange(questions);
                    }
                }

                for (int i = 0; i < 3; i++)
                {
                    if (instExamVM.NoOfTF[i] != 0)
                    {
                        var questions = allQuestionsDto.Where(q => q.Type == QType.TrueFalse && q.Difficulty == (QDifficulty)(i + 1))
                                                      .OrderBy(q => _random.Next())
                                                      .Take(instExamVM.NoOfTF[i])
                                                      .ToList();

WebAppProject/Areas/Staff/Views/Instructor/AddQuestion.cshtml
@model QuestionViewModel

@{
    ViewData["Title"] = "Add Question - Examly";
}
<indicator hidden>inst-courses</indicator>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">New Question</p>
                <div class="row">
                    <div class="col-12">
                        <form asp-action="AddQuestion" asp-controller="Instructor" method="post">

                            <input type="hidden" asp-for="InstructorId" value="@Model.InstructorId" />
                            <input type="hidden" asp-for="CourseId" value="@Model.CourseId" />

                            <div class="row m-1 mb-0">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label asp-for="Type">Question Type</label>
                                        <select asp-for="Type" id="questionType" class="form-control"
                                                asp-items="Html.GetEnumSelectList<QVMType>()">
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <partial name="QuestionPartial" />

                            <button type="submit" asp-route-courseId="@Model.CourseId" class="btn btn-primary">Add Question</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/lib/jquery/dist/jquery.js"></script>
@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var questionTypeSelect = document.getElementById("questionType");
            $("#choicesContainer").load("/Staff/Instructor/AddChoices/1");

            questionTypeSelect.addEventListener("change", function () {
                var type = this.value;
                if (type === '1') {
                    $("#choicesContainer").load("/Staff/Instructor/AddChoices/1");
                } else if (type === '2') {
                    $("#choicesContainer").load("/Staff/Instructor/AddChoices/2");
                }
            });
        });
        document.querySelector('form').addEventListener("submit", function () {
            if (document.querySelector('#trueFalseContainer') !== undefined) {
                console.log(document.querySelector('input[type=radio]:not(:checked)').value);

                document.querySelector('#incorrectChoice').value =
                document.querySelector('input[type=radio]:not(:checked)').value;
            }
        });
    </script>
}

WebAppProject/Areas/Staff/Views/Instructor/ExamEdit.cshtml
@model InstExamViewModel

@{
    ViewData["Title"] = "Edit Exam - Examly";
}
<indicator hidden>inst-exams</indicator>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Edit Exam</p>
                <div class="row">
                    <div class="col-12">
                        <p><strong>Course</strong> @Model.CourseName</p>
                        <form asp-action="EditExam" method="post">
                            <input asp-for="Id" value="@Model.Id" hidden />
                            <input asp-for="TotalGrade" value="@Model.TotalGrade" hidden />
                            <partial name="ExamEditPartial" />
                            <br />
                            <div class="d-flex justify-content-end">
                                <a asp-action="ShowExams" class="btn btn-inverse-dark m-2">Cancel</a>
                                <button type="submit" asp-route-id="@Model.CourseId" class="btn btn-primary m-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@if (Model.Questions != null)
{
    for (int i = 0; i < Model.Questions.Count; i++)
    {
        var question = Model.Questions[i];
        string badgeColor = question.Difficulty == QVMDifficulty.Easy ? "badge-success" :
                        question.Difficulty == QVMDifficulty.Medium ? "badge-warning" :
                        "badge-danger";
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-title">Q @(i + 1)</p>
                        <div class="row">
                            <div class="col-md-6 align-content-center">
                                <p class="font-weight-bold">Question</p>
                                <p>@question.Text</p>
                                <p class="font-weight-bold">Difficulty</p>
                                <label class="badge @badgeColor">@question.Difficulty</label>
                                <p class="font-weight-bold">Type</p>
                                <p>@(question.Type == QVMType.MCQ ? "Multiple Choices" : " Ture / False")</p>
                                <p class="font-weight-bold">Grade</p>
                                <p>@question.Grade</p>
                            </div>

                            <div class="col-md-6">
                                <p class="font-weight-bold pt-3">Choices</p>
                                @foreach (var choice in question.Choices)
                                {

                                    <div class="form-group">
                                        <div class="input-group">
                                            <input type="text" class="form-control" value="@choice.Text" readonly />
                                            <div class="input-group-append">
                                                <button disabled class="btn btn-sm @(@choice.IsCorrect ? "btn-success" : "btn-danger")">
                                                    <i class="mdi @(choice.IsCorrect ? "mdi-check" : "mdi-close")"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}

WebAppProject/Areas/Staff/Views/Instructor/ExamEditPartial.cshtml
@model InstExamViewModel
@{
    string formattedDateTime = Model.ExamDate.ToString("yyyy-MM-ddTHH:mm");
}

<div class="row m-1">
    <div class="col-md-4">
        <input type="hidden" asp-for="CourseId" value="@Model.CourseId" />
        <input type="hidden" asp-for="DepartmentId" value="@Model.DepartmentId" />

        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" value="@Model.Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ExamDate">Date</label>
        <input asp-for="ExamDate" value="@formattedDateTime" class="form-control" />
            <span asp-validation-for="ExamDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DurationInMinutes">Duration in minutes</label>
            <input asp-for="DurationInMinutes" value="@Model.DurationInMinutes" class="form-control" />
            <span asp-validation-for="DurationInMinutes" class="text-danger"></span>
        </div>
    </div>
</div>  

WebAppProject/Areas/Staff/Views/Instructor/ExamGrades.cshtml
@model IEnumerable<StaffExamTakenViewModel>

@{
    ViewData["Title"] = "Exam Grades - Examly";
    string examTitle = Model != null && Model.Count() > 0 ? " - " + @Model.ElementAt(0).ExamTitle : string.Empty;
}
<indicator hidden>inst-exams</indicator>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Grades @examTitle</p>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table display expandable-table">
                                <thead>
                                    <tr>
                                        <th>Student</th>
                                        <th>Progress</th>
                                        <th>Grade</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null && Model.Count() > 0)
                                    {
                                        foreach (var examTaken in Model)
                                        {
                                            int percentage = (int)(((double)examTaken.Grade / examTaken.TotalGrade) * 100);
                                            string progressColor = percentage <= 49 ? "bg-danger" : percentage <= 79 ? "bg-warning" : "bg-success";
                                            <tr>
                                                <td>@examTaken.StudentName</td>
                                                <td>
                                                    <div class="progress">
                                                        <div class="progress-bar @progressColor" role="progressbar" style="width: @(percentage)%" aria-valuemax="100"></div>
                                                    </div>
                                                </td>
                                                <td>@examTaken.Grade</td>
                                                <td class="col-1">
                                                    <a type="button"
                                                       asp-action="StudentAnswers" asp-route-examId="@examTaken.ExamId"
                                                       asp-route-stdId="@examTaken.StudentId"
                                                       class="btn btn-inverse-primary btn-sm ml-1">
                                                        Answers
                                                    </a>
                                                </td>
                                            </tr>

                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="4">No grades for this exam!</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebAppProject/Areas/Staff/Views/Instructor/Index.cshtml
@model IEnumerable<DeptCourseViewModel>
@{
    ViewData["Title"] = "Examly";
}
<indicator hidden>inst-courses</indicator>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Courses Taught</p>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table display expandable-table">
                                <thead>
                                    <tr>
                                        <th>Department Name</th>
                                        <th>Course Name</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.DeptName</td>
                                            <td>@item.CourseName</td>

                                            <td class="col-1">
                                                <a type="button"
                                                        asp-action="Info" asp-route-id="@item.CourseId"
                                                        class="btn btn-inverse-dark btn-rounded btn-icon ml-1">
                                                    <i class="mdi mdi-information-variant"></i>
                                                </a>
                                                <a type="button"
                                                        asp-action="QuestionBank" asp-route-id="@item.CourseId"
                                                   class="btn btn-inverse-primary btn-sm ml-1">
                                                    Questions
                                                </a>
                                                <a type="button"
                                                        asp-action="MakeExam" asp-route-deptId="@item.DepartmentId" asp-route-courseId="@item.CourseId"
                                                   class="btn btn-inverse-primary btn-sm ml-1">
                                                   Make Exam
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>