WebAppProject/Areas/Admin/ViewModels/DepartmentViewModel.cs
using DataAccessLibrary.Model;
using System.ComponentModel.DataAnnotations;

namespace WebAppProject.Areas.Admin.ViewModels
{
    public class DepartmentViewModel
    {
        public int Id { get; set; }

        [MinLength(2, ErrorMessage = "Name must be at least 2 characters.")]
        [RegularExpression(@"[a-zA-Z-]+", ErrorMessage = "Name must contain only characters")]
        public string Name { get; set; }
        public string? ManagerName { get; set; }
        public DateTime? HireDate { get; set; }
        public string? BranchName { get; set; }
    }
}

WebAppProject/Areas/Staff/ViewModels/DepartmentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAppProject.Areas.Staff.ViewModels
{
    public class DepartmentViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "The department name is required.")]
        [MinLength(2, ErrorMessage = "Name must be 2 characters or more.")]
        [RegularExpression(@"[a-zA-Z-]+", ErrorMessage = "Name must contain only characters")]

        public string Name { get; set; }

        //public IEnumerable <CourseInfoViewModel> DepartmentCourse { get; set; }
        public ICollection<CourseInfoViewModel> DepartmentCourses { get; } = new List<CourseInfoViewModel>();


    }
}

WebAppProject/ViewModels/DepartmentViewModel.cs
namespace WebAppProject.ViewModels
{
    public class DepartmentViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

WebAppProject/Areas/Admin/Controllers/DepartmentController.cs
using AutoMapper;
using DataAccessLibrary.Interfaces;
using DataAccessLibrary.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppProject.Areas.Admin.ViewModels;



namespace WebAppProject.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area(areaName: "Admin")]
    public class DepartmentController : Controller
    {

        private readonly IDepartmentRepository departmentRepository;
        private readonly IBranchRepository branchRepository;
        private readonly IMapper _mapper;

        public DepartmentController(IDepartmentRepository departmentRepository, IBranchRepository branchRepository, IMapper mapper)
        {
            this.departmentRepository = departmentRepository;
            this.branchRepository = branchRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Details(int Id)
        {
            IActionResult actionResult;
            Department? department = await departmentRepository.GetByIdWithIncludesAsync(Id);
            if (department != null)
            {
                var model = _mapper.Map<AdminDepartmentViewModel>(department);
                actionResult = View(model);
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }
        public async Task<IActionResult> Create()
        {
            var branches = await branchRepository.GetAllAsync();
            var branchesDtos = _mapper.Map<List<BranchViewModel>>(branches);
            var model = new DepartmentFormViewModel() { Branches = branchesDtos };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(DepartmentFormViewModel model)
        {

            IActionResult actionResult;
            if (ModelState.IsValid)
            {
                Department department = _mapper.Map<Department>(model);
                int res = await departmentRepository.AddAsync(department);
                actionResult = res > 0 ? RedirectToAction("Index", "Manage") : RedirectToAction("Create");
            }
            else
            {
                var branches = await branchRepository.GetAllAsync();
                model.Branches = _mapper.Map<List<BranchViewModel>>(branches);
                actionResult = View(model);
            }
            return actionResult;
        }
        public async Task<IActionResult> Edit(int Id)
        {
            IActionResult actionResult;
            Department? department = departmentRepository.GetByIdWithIncludes(Id);
            if (department != null)
            {
                var model = _mapper.Map<DepartmentFormViewModel>(department);
                var branches = await branchRepository.GetAllAsync();
                model.Branches = _mapper.Map<List<BranchViewModel>>(branches);

                actionResult = View(model);
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DepartmentFormViewModel model)
        {
            IActionResult actionResult;
            if (ModelState.IsValid)
            {
                var department = _mapper.Map<Department>(model);
                bool res = await departmentRepository.UpdateAsync(department);
                actionResult = res ? RedirectToAction("Index", "Manage") : RedirectToAction("Edit", model.Id);
            }
            else
            {
                var branches = await branchRepository.GetAllAsync();
                model.Branches = _mapper.Map<List<BranchViewModel>>(branches);
                actionResult = View(model);
            }
            return actionResult;
        }

        public async Task<IActionResult> Delete(int Id)
        {
            IActionResult actionResult;
            Department? department = await departmentRepository.GetByIdWithIncludesAsync(Id);
            if (department != null)
            {
                var model = _mapper.Map<AdminDepartmentViewModel>(department);
                actionResult = View(model);
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }

        [HttpPost]
        public async Task<IActionResult> Delete(AdminDepartmentViewModel model)
        {
            IActionResult actionResult;
            Department? department = await departmentRepository.GetByIdWithIncludesAsync(model.Id);
            if (department != null)
            {
                await departmentRepository.DeleteAsync(department.Id);
                actionResult = RedirectToAction("Index", "Manage");
            }
            else
            {
                actionResult = BadRequest();
            }
            return actionResult;
        }
    }
}

WebAppProject/Areas/Admin/Views/Department/Create.cshtml
@{
    ViewData["Title"] = "Create Department - Examly";
    ViewData["FormTitle"] = "Create Department";
}
<indicator hidden>admin-dash</indicator>
<partial name="DepartmentForm" />

WebAppProject/Areas/Admin/Views/Department/Delete.cshtml
@model AdminDepartmentViewModel
@{
    ViewData["Title"] = "Delete Department - Examly";
}
<indicator hidden>admin-dash</indicator>
<div class="row justify-content-center">
    <div class="col-md-8 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Delete Department</p>
                <div class="row">
                    <div class="col-12">
                        <h3 class="card-text"> Are you sure you want to delete <strong>@Model.Name Department?</strong></h3>
                        <form method="post" class="forms-sample  mt-3">
                            <div class="form-group ">
                                <input type="submit" value="Delete" class="btn btn-danger mr-2" />
                                <a asp-action="Index" asp-controller="Manage" class="btn btn-light">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebAppProject/Areas/Admin/Views/Department/DepartmentForm.cshtml
@model DepartmentFormViewModel

@{
    SelectList BranchesItems = new SelectList(Model.Branches, "Id", "Name");
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">@ViewData["FormTitle"]</p>
                <div class="row">
                    <div class="col-12">
                        <form method="post" class="forms-sample">
                            <div class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group ">
                                <label class="control-label">Branch</label>
                                <select asp-for="BranchId" class="form-control" asp-items="BranchesItems">
                                    <option value="-1">Select Branch</option>
                                </select>
                                <span asp-validation-for="BranchId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Confirm" class="btn btn-primary mr-2" />
                                <a asp-action="Index" asp-controller="Manage" class="btn btn-light">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebAppProject/Areas/Admin/Views/Department/Details.cshtml
@model AdminDepartmentViewModel
@{
    ViewData["Title"] = "Department Details - Examly";
    string managerName = Model.ManagerName ?? "No Manager";
    string managerDate = Model.HireDate?.ToString() ?? "No Hire Date";
}
<indicator hidden>admin-dash</indicator>
<div class="row justify-content-center">
    <div class="col-md-8 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <p class="card-title m-0">Department Details</p>
                    <div>
                        <a asp-action="Edit" asp-controller="Department" asp-route-Id="@Model.Id" class="btn btn-inverse-primary btn-rounded btn-icon ml-1 align-content-center">
                            <i class="mdi mdi-pencil"></i>
                        </a>
                        <a asp-action="Delete" asp-controller="Department" asp-route-Id="@Model.Id" class="btn btn-inverse-danger btn-rounded btn-icon ml-1 align-content-center">
                            <i class="mdi mdi-delete"></i>
                        </a>
                        <a asp-action="Index" asp-controller="Manage"
                           class="btn btn-inverse-dark btn-rounded btn-icon ml-1 align-content-center">
                            <i class="mdi mdi-close"></i>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <p class="card-text">ID: <strong> @Model.Id</strong> </p>
                        <p class="card-text">Name: <strong>@Model.Name </strong></p>
                        <p class="card-text">Name: <strong>@Model.BranchName </strong></p>
                        <p class="card-text">Manager Name: <strong>@managerName</strong></p>
                        <p class="card-text">Manager Hiring date: <strong>@managerDate</strong></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebAppProject/Areas/Admin/Views/Department/Edit.cshtml
@{
    ViewData["Title"] = "Edit Department - Examly";
    ViewData["FormTitle"] = "Edit Department";
}
<indicator hidden>admin-dash</indicator>
<partial name="DepartmentForm" />